### ISSUE TITLE
Txt file not found

### ISSUE THREAD

**Issue by dthmax** [corbin-hayden13/SD-Lora-Tagger#17]
Hello, sorry i dont know very well what happend but i was using stability matrix and the version 1.8.0-RC of Stable difussion Web-UI and got this error.

Can it be that i have to creat a .txt for every lora that i have before launching ?

Thanks for your work!

The log:

Traceback (most recent call last):
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\extensions\SD-Lora-Tagger\scripts\helpers\registration_override.py", line 187, in list_items
    with open(os.path.join(self.descriptions_path,
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Prueba\\Data\\Packages\\Stable Diffusion WebUI\\extensions\\SD-Lora-Tagger\\network_descriptions/Lora/1713909428413834009.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\modules\ui_extra_networks.py", line 694, in pages_html
    create_html()
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\modules\ui_extra_networks.py", line 690, in create_html
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\modules\ui_extra_networks.py", line 690, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\modules\ui_extra_networks.py", line 510, in create_html
    self.items = {x["name"]: x for x in self.list_items()}
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\modules\ui_extra_networks.py", line 510, in <dictcomp>
    self.items = {x["name"]: x for x in self.list_items()}
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\extensions\SD-Lora-Tagger\scripts\helpers\registration_override.py", line 192, in list_items
    with open(os.path.join(self.descriptions_path,
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Prueba\\Data\\Packages\\Stable Diffusion WebUI\\extensions\\SD-Lora-Tagger\\network_descriptions/Lora/1713909428413834009.txt'
Traceback (most recent call last):
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\extensions\SD-Lora-Tagger\scripts\helpers\registration_override.py", line 187, in list_items
    with open(os.path.join(self.descriptions_path,
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Prueba\\Data\\Packages\\Stable Diffusion WebUI\\extensions\\SD-Lora-Tagger\\network_descriptions/Lora/1713909428413834009.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\modules\ui_extra_networks.py", line 694, in pages_html
    create_html()
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\modules\ui_extra_networks.py", line 690, in create_html
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\modules\ui_extra_networks.py", line 690, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\modules\ui_extra_networks.py", line 510, in create_html
    self.items = {x["name"]: x for x in self.list_items()}
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\modules\ui_extra_networks.py", line 510, in <dictcomp>
    self.items = {x["name"]: x for x in self.list_items()}
  File "D:\Prueba\Data\Packages\Stable Diffusion WebUI\extensions\SD-Lora-Tagger\scripts\helpers\registration_override.py", line 192, in list_items
    with open(os.path.join(self.descriptions_path,
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Prueba\\Data\\Packages\\Stable Diffusion WebUI\\extensions\\SD-Lora-Tagger\\network_descriptions/Lora/1713909428413834009.txt'
Applying attention optimization: xformers... done.
Model loaded in 26.0s (load weights from disk: 4.1s, create model: 0.9s, apply weights to model: 19.1s, load textual inversion embeddings: 0.3s, calculate empty prompt: 1.4s).

**Comment by corbin-hayden13** [comment]
Thanks for the report!  Currently, .txt files should be automatically generated for every network you have downloaded so you don't have to manually create them.  I'll take a look at the issue and figure out why this occurred,  For this specific Lora though, do you have it in a sdubdirectory of your "models/Lora" folder?

**Comment by corbin-hayden13** [comment]
@dthmax It looks like you're using an old version of the extension, as I remember this issue and we created a patch for it a day or two ago.  I would suggest updating your extension and if this problem persists, please create a new issue with the new error log.  Hopefully this helps!
